/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonNav: typeof import('./src/components/common-nav/common-nav.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MoreButton: typeof import('./src/components/common-nav/more-button.vue')['default']
    MoreLink: typeof import('./src/components/common-nav/more-link.vue')['default']
    NavHeader: typeof import('./src/components/common-nav/nav-header.vue')['default']
    NavItem: typeof import('./src/components/common-nav/nav-item.vue')['default']
    NavList: typeof import('./src/components/common-nav/nav-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanIcon: typeof import('vant/es')['Icon']
    VHtml: typeof import('./src/components/v-html/index.vue')['default']
  }
}
